### PR TITLE
Migration to 1.18(.1)

### PR DESCRIPTION
**Pull request by lochnessdragon**
I've started the migration to 1.18.1.
So far, I've:
1) Updated gradle wrapper to 7.1
2) Updated maven repo, forge gradle to 5.+ and mc version to 1.18.1
  a) Added configuration options to gradle.properies to make it easier to change mc versions in the future
3) Ran ```gradlew updateMappings``` with the target being the official 1.18 mappings
4) Fixed all mappings in the ```me.paulf.fairylights.util``` package.

### CODE REVIEW

**Comment by BlackJamesYT** [comment]
Does-it fully work ?

**Comment by lochnessdragon** [comment]
Sadly not, its a lot of code to get to, including a potential coremod. I’ve been working through the packages, but I figured the util package would be a good place to start.

**Comment by BlackJamesYT** [comment]
Ok I see ! Nice work until now 😁

**Comment by allaryin** [comment]
Should probably bump this effort to 1.18.2 before you get much deeper. I doubt that'll involve much more than the version number bump, but better to be safe than sorry ;)

**Comment by tobybug** [comment]
lochnessdragon, I really appreciate your efforts to upgrade the mod, as it's one of my modpack must-haves. I heard there was some changes between 1.18.1 to 1.18.2 involving the way the game handles item tags? The linked forum post may or may not be useful: https://forums.minecraftforge.net/topic/109200-1182-and-tag-changes/
I was just wondering how much effort it would be to leapfrog to 1.18.2, if that's something you're considering. Have a nice day ^_^

**Comment by mimi-min** [comment]
I appreciate this too! I'm using 1.19, but even just getting it to 1.18 is a huge feat, and I'm sure it will be easier to get to 1.19 from there!

I don't know if you're still working on it since it's been a few months, but know that there are people out there rooting for you regardless ♡

**Comment by JordgyPordgy** [comment]
This is one of my favorite mods for minecraft EVER and I can't wait for it to get updated! Whatever we can do to help support you, please let us know! <3

**Comment by xElandriax** [comment]
> I've started the migration to 1.18.1. So far, I've:


Any update to the work you were doing? :)

**Comment by pau101** [comment]
Fairy Lights is now available for 1.18.2 and 1.19.2

**Pull request closed without merging**
